# Porta da aplicação
server.port=8080

# Nome da aplicação para uso em logs e monitoramento
spring.application.name=deliverytech-api

# Banco de dados H2
spring.datasource.url=jdbc:h2:file:./data
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=4321
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA e Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configurações de cache
spring.cache.type=simple

# --- Swagger OpenAPI ---
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
# Habilitar a exibição dos endpoints do Actuator no Swagger UI
springdoc.show-actuator=true
# Agrupar os endpoints da sua API de negócio
springdoc.group-configs[0].group=1. DeliveryTech API
springdoc.group-configs[0].paths-to-match=/api/**
# Agrupar os endpoints do Actuator
springdoc.group-configs[1].group=2. Actuator Monitoring
springdoc.group-configs[1].paths-to-match=/actuator/**

# --- Configurações de Observabilidade e Monitoramento ---
# Expor os endpoints do Actuator para monitoramento
management.endpoints.web.exposure.include=*
# Mostrar detalhes completos no endpoint /actuator/health
management.endpoint.health.show-details=always
# Adiciona um padrão de log que com informações de treacing (Trace ID e Span ID)
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
# Configurar a probabilidade de amostragem de traces (1.0 = 100% do traces serão enviados)
management.tracing.sampling.probability=1.0

# Segurança
spring.security.user.name=admin
spring.security.user.password=admin123

# Desenvolvimento
spring.devtools.restart.enabled=true
    
# Nível de log da aplicação
logging.level.root=INFO
logging.level.com.deliverytech=DEBUG
#spring.devtools.restart.enabled=false
